#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.1
#  in conjunction with Tcl version 8.6
#    Jun 20, 2022 09:45:30 PM CEST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
#from PIL import ImageTk, Image
import os
from tkinter import messagebox
import configparser

import JanaTTT_support

global playmode


def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(JanaTTT_support.root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.post(event.x_root, event.y_root)

def popup2(event, *args, **kwargs):
        Popupmenu2 = tk.Menu(JanaTTT_support.root, tearoff=0)
        Popupmenu2.configure(activebackground="#f9f9f9")
        Popupmenu2.post(event.x_root, event.y_root)


#get playmode
config = configparser.ConfigParser()
config.read('spiel.ini')
playmode = config['DEFAULT']['playmode']


class Toplevel1:
    def __init__(self, top=None):
        
        
        def save_play_mode():
            global playmode
            spielmodus = self.TCombobox1.get()
            config = configparser.ConfigParser()
            config.read('spiel.ini')
            config['DEFAULT']['playmode'] = spielmodus
            with open('spiel.ini', 'w') as configfile:    # save
                config.write(configfile)
            playmode = spielmodus
        
        
        
        def spiel_start():
            print(playmode)
            if playmode =='2 Spieler':
                os.system("python3 jgame.py 1")
            elif playmode =='Simple Engine':
                os.system("python3 jgame2.py 1")
            elif playmode =='Normal Engine':
                os.system("python3 jgame3.py 1")
            
            
            
        def symbole_waehlen():

            os.system("python3 Jana_Symbole.py 1")
        
        def hello():
            messagebox.showinfo("About JanaTTT", "Dies ist ein Gemeinschaftsprojekt von Jana und Ricky Helfgen")
        
        
        
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("450x400+383+106")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1,  1)
        top.title("Janas Tic Toc Toe")
        top.configure(highlightcolor="black")
        
        
        img = tk.PhotoImage(file='315483.png')

        top.wm_iconphoto(True, img)
        
        
            
        
        self.top = top
        
        
        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.menubar.add_command(
                command=symbole_waehlen,
                label="Symbole wählen")
        self.menubar.add_command(
                command=spiel_start,
                label="Spiel starten")
        self.menubar.add_command(
                command=hello,
                label="Über JanaTTT")


        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.01, rely=0.08, height=400, width=450)
        self.Label1.configure(anchor='w')
        self.Label1.configure(compound='left')
        photo_location = "Jana_logo.gif"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)
        



        self.TCombobox1 = ttk.Combobox(self.top)
        self.TCombobox1.place(relx=0.01, rely=0.01, relheight=0.072
                , relwidth=0.3)
        self.value_list1 = ['2 Spieler','Simple Engine', 'Normal Engine']
        
        self.TCombobox1.configure(values=self.value_list1)
        self.TCombobox1.current(0)
        self.TCombobox1.configure(takefocus="")        
        
        
        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.35, rely=0.01, height=33, width=200)
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(compound='left')
        self.Button1.configure(text='''Spieler Modus speichern''')
        self.Button1.configure(command=save_play_mode)
        
        
        
        
        #Imtk1 = tk.PhotoImage(file="X_modified.png")
        #self.(False, Imtk1)



def start_up():
    JanaTTT_support.main()

if __name__ == '__main__':
    JanaTTT_support.main()




