#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.1
#  in conjunction with Tcl version 8.6
#    Jun 21, 2022 10:36:37 PM CEST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import glob
import configparser

import Jana_Symbole_support




class Toplevel1:
    def __init__(self, top=None):
        
        
        
        def showing(e):
            global _img0
            n = self.Listbox1.curselection()
            fname = self.Listbox1.get(n)
            _img0 = tk.PhotoImage(file=fname)
            self.Label2.configure(image=_img0)
            print(fname)
        
        
        def set_player1():
            print('Set Player 1 :',_img0 )
            anderes_Bild = self.Label4.cget('text')
            n = self.Listbox1.curselection()
            bild1 = self.Listbox1.get(n)
                
            if bild1 == anderes_Bild:
                print('Bild schon besetzt')
            else:
                self.Label3.configure(text=bild1)
        
        def set_player2():
            print('Set Player 2 :',_img0)
            anderes_Bild = self.Label3.cget('text')
            n = self.Listbox1.curselection()
            bild2 = self.Listbox1.get(n)
            
            if bild2 == anderes_Bild:
                print('Bild schon besetzt')
            else:
                self.Label4.configure(text=bild2)

        def save_player():
            print('Spieler Daten speichern')
            
            bild1 = self.Label3.cget('text')
            print(bild1)
            
            if bild1 =='Spieler1':
                bild1 ='o-modified.png'
            else:
                bild1 = bild1
            
            bild2 = self.Label4.cget('text')
            
            print(bild2)
            if bild2 =='Spieler2':
                bild2 ='x-modified.png'
            else:
                bild2 = bild2
            
            config = configparser.ConfigParser()
            config.read('spiel.ini')
            config['DEFAULT']['bild1'] = bild1
            config['DEFAULT']['bild2'] = bild2
            with open('spiel.ini', 'w') as configfile:    # save
                config.write(configfile)
            
            
            
        
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x548+383+106")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1,  1)
        top.title("Jana Tic Tac Toe - Symbole wählen")

        self.top = top


        namelist = [i for i in glob.glob("*png")]
        



        self.Listbox1 = tk.Listbox(self.top)
        self.Listbox1.place(relx=0.017, rely=0.128, relheight=0.85
                , relwidth=0.407)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font="TkFixedFont")
        for fname in namelist:
            self.Listbox1.insert(tk.END, fname)
            self.Listbox1.bind("<<ListboxSelect>>", showing)

        
        
        

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.017, rely=0.091, height=21, width=199)
        self.Label1.configure(anchor='w')
        self.Label1.configure(compound='left')
        self.Label1.configure(text='''Wähle ein Symbol:''')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.433, rely=0.12, height=33, width=73)
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(compound='left')
        self.Button1.configure(text='''Spieler 1''')
        self.Button1.configure(command=set_player1)
        
        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.433, rely=0.2, height=21, width=199)
        self.Label3.configure(anchor='w')
        self.Label3.configure(compound='left')
        self.Label3.configure(text='''Spieler1''')
        
        
        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.75, rely=0.12, height=33, width=73)
        self.Button2.configure(borderwidth="2")
        self.Button2.configure(compound='left')
        self.Button2.configure(text='''Spieler 2''')
        self.Button2.configure(command=set_player2)
        
        self.Label4 = tk.Label(self.top)
        self.Label4.place(relx=0.75, rely=0.2, height=21, width=199)
        self.Label4.configure(anchor='w')
        self.Label4.configure(compound='left')
        self.Label4.configure(text='''Spieler2''')
        
        
        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.45, rely=0.274, height=300, width=300)
        self.Label2.configure(anchor='w')
        self.Label2.configure(compound='left')
        photo_location = "X_modified.png"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label2.configure(image=_img0)

        
 

        
        
        
        
        
        
        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.65, rely=0.900, height=33, width=200)
        self.Button3.configure(borderwidth="2")
        self.Button3.configure(compound='left')
        self.Button3.configure(text='''Symbole zuweisen''')
        self.Button3.configure(command=save_player)
        
        

def start_up():
    Jana_Symbole_support.main()

if __name__ == '__main__':
    Jana_Symbole_support.main()




