#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.1
#  in conjunction with Tcl version 8.6
#    Jun 20, 2022 09:45:14 PM CEST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import JanaTTT

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = JanaTTT.Toplevel1(_top1)
    root.mainloop()

def info(*args):
    print('JanaTTT_support.info')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def spiel_start(*args):
    print('JanaTTT_support.spiel_start')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def spieler_wählen(*args):
    print('Janas_TTT_support.spieler_wählen')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

if __name__ == '__main__':
    JanaTTT.start_up()




