#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.1
#  in conjunction with Tcl version 8.6
#    Jun 20, 2022 09:45:30 PM CEST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
#from PIL import ImageTk, Image
import os
from tkinter import messagebox

import JanaTTT_support

def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(JanaTTT_support.root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.post(event.x_root, event.y_root)

def popup2(event, *args, **kwargs):
        Popupmenu2 = tk.Menu(JanaTTT_support.root, tearoff=0)
        Popupmenu2.configure(activebackground="#f9f9f9")
        Popupmenu2.post(event.x_root, event.y_root)

class Toplevel1:
    def __init__(self, top=None):
        
        
        def spiel_start():

            os.system("python3 jgame.py 1")

        def symbole_waehlen():

            os.system("python3 Jana_Symbole.py 1")
        
        def hello():
            messagebox.showinfo("About JanaTTT", "Dies ist ein Gemeinschaftsprojekt von Jana und Ricky Helfgen")
        
        
        
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("450x400+383+106")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1,  1)
        top.title("Janas Tic Toc Toe")
        top.configure(highlightcolor="black")
        
        
        img = tk.PhotoImage(file='315483.png')

        top.wm_iconphoto(True, img)
        
        self.top = top
        
        
        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.menubar.add_command(
                command=symbole_waehlen,
                label="Symbole wählen")
        self.menubar.add_command(
                command=spiel_start,
                label="Spiel starten")
        self.menubar.add_command(
                command=hello,
                label="Über JanaTTT")


        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.01, rely=0.01, height=400, width=450)
        self.Label1.configure(anchor='w')
        self.Label1.configure(compound='left')
        photo_location = "Jana_logo.gif"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)
        
        
        #Imtk1 = tk.PhotoImage(file="X_modified.png")
        #self.(False, Imtk1)



def start_up():
    JanaTTT_support.main()

if __name__ == '__main__':
    JanaTTT_support.main()




